# Generated by Django 6.0.1 on 2026-02-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fav',
            field=models.ImageField(blank=True, null=True, upload_to='fav/'),
        ),
    ]
